package:
  name: blasr
  version: "5.1"

build:
  number: 0

source:
  git_url: https://github.com/PacificBiosciences/blasr.git
  git_rev: ec4144fd3195d62c182678594172ab6f68b5d7fc

  patches:
    - blasr.patch

requirements:
  build:
  - gcc # [not osx]
  - llvm # [osx]
  - hdf5
  - git

  run:
  - libgcc # [not osx]
  - hdf5

# test:
#   commands:
#     - blasr --version

about:
  home: https://github.com/PacificBiosciences/blasr
  license: BSD-3-Clause-Clear
  license_file: LICENSE
  summary: BLASR - The PacBio long read aligner

